# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_ticker_sym', models.CharField(max_length=4)),
                ('stock_name', models.CharField(max_length=200)),
                ('curr_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=999)),
                ('purc_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=999)),
                ('share_number', models.DecimalField(decimal_places=2, default=0.0, max_digits=999)),
                ('last_update', models.DateTimeField(verbose_name='last updated')),
                ('purc_date', models.DateTimeField(verbose_name='purchase date')),
                ('price_diff', models.DecimalField(decimal_places=2, default=0.0, max_digits=999)),
            ],
        ),
    ]
